[font]
normal = { family = "CaskaydiaCove NF", style = "Light" }
bold = { style = "Regular" }
italic = { style = "Light Italic" }
bold_italic = { style = "Italic" }
size = 14

[cursor]
style = { shape = "Underline", blinking = "On" }
blink_timeout = 0
blink_interval = 500
thickness = 0.25

[keyboard]
bindings = [
	{ key = "Right", mods = "Alt", chars = "\u001BF" },
	{ key = "Left", mods = "Alt", chars = "\u001BB" },
]
